include $(RIOTBOARD)/common/makefiles/stdio_cdc_acm.dep.mk

ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += bme680_i2c
endif

ifneq (,$(filter stdio_cdc_acm,$(USEMODULE)))
  # The Mask-ROM bootloader provides USB-DFU capability
  FEATURES_REQUIRED += bootloader_stm32
  USEMODULE += usb_board_reset
endif
